spring.application.name=products

server.port=30000

spring.datasource.url=jdbc:postgresql://aws-0-us-east-2.pooler.supabase.com:5432/teraha
spring.datasource.username=postgres.bboesrmuocbuqaqoaswr
spring.datasource.password=${DB_PASSWORD}

springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true

spring.jpa.open-in-view=false

products.paging.page-size=2

logging.level.org.springframework.data.jpa.repository=DEBUG
logging.level.org.hibernate.SQL=DEBUG
